# CONVERTING PYTHON SEQUENCES TO NUMPY ARRAYS
Key thing to note here is to specify the type of elements that will be in the array. This gives more control over the underlying data structures and how the elements are handled C/C++ functions 

In [2]:
# Numpy arrays can be defined using python sequences such as lists and tuples
# A list of numbers will create a 1D array
import numpy as np
a1D = np.array([1,2,3,4])
print("a1D = \n", a1D)
# A list of lists will create a 2D array
a2D = np.array([[1,2,3,4],[5,6,7,8]])
print("a2D = \n", a2D)
# Nested lists will create higher dmensional arrays
a3D = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print("a3D = \n", a3D)

a1D = 
 [1 2 3 4]
a2D = 
 [[1 2 3 4]
 [5 6 7 8]]
a3D = 
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


# INTRINCSIC NUMPY ARRAY CREATION FUNCTIONS
Numpy has 40 built-in functions for creating arrays. These are split into 3 based on dimension of the arrays
1. 1D arrays
2. 2D arrays
3. ndarrays

# 1D Array creation functions - np.linspace & np.arange

In [3]:
#Using np.arange
#Note arange doesn't include the end value
a = np.arange(10)
print("a=\n",a)
b = np.arange(2,10,dtype='float')
print("b=\n",b)
c = np.arange(2,6,0.2) #this is the best practice in using np.arange = start,end and step values
print("c=\n",c)

#Using np.linspace - This will create array with specified number of elements equally spaced in btw start and stop values
#Advantage of this is that start and end values are certain including number of elements in the array
d = np.linspace(1,7,10)
print("d=\n", d)


a=
 [0 1 2 3 4 5 6 7 8 9]
b=
 [2. 3. 4. 5. 6. 7. 8. 9.]
c=
 [2.  2.2 2.4 2.6 2.8 3.  3.2 3.4 3.6 3.8 4.  4.2 4.4 4.6 4.8 5.  5.2 5.4
 5.6 5.8]
d=
 [1.         1.66666667 2.33333333 3.         3.66666667 4.33333333
 5.         5.66666667 6.33333333 7.        ]


# 2D Array Creation Functions - np.eye, np.diag, np.vander 

In [4]:
#Using np.eye to create identity matrix
i = np.eye(3) #3X3 identity matrix
print("3 by 3 identity matrix =\n", i)
ii = np.eye(3,5) #3X5 inhomogenous identity matrix
print("3 by 5 identity matrix =\n", ii)

#Using np.diag to create a diagonal matrix
#This can define a 2D array with given elements along the diagonal &
#This can also return the diagonal elements if given a 2D array
di = np.diag([1,2,3])
print("Given diagonal elements, diagonal Matrix =\n", di)
do = np.array([[1,2], [4,5]])
do = np.diag(do)
print("Diagonal matrix of Array =\n", do)

3 by 3 identity matrix =
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
3 by 5 identity matrix =
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]
Given diagonal elements, diagonal Matrix =
 [[1 0 0]
 [0 2 0]
 [0 0 3]]
Diagonal matrix of Array =
 [1 5]


# VANDERMONDE MATRIX
vander(x,n) defines a vadermonde matrix as a 2D numpy array
Each column of the matrix is a decreasing power of the input 1D array or list or tuple
This vandermonde matrix is useful in generating linear least squares models

In [5]:
#Examples on vandermonde matrix
van1 = np.vander([1,2,3,4],4) #create vander matrix of 4 columns
print("Vandermonde matrix =\n", van1)
van2 = np.vander(np.linspace(0,2,5),3) #Create a vander matrix of 3 columns
print("Vandermonde matrix = \n", van2)

Vandermonde matrix =
 [[ 1  1  1  1]
 [ 8  4  2  1]
 [27  9  3  1]
 [64 16  4  1]]
Vandermonde matrix = 
 [[0.   0.   1.  ]
 [0.25 0.5  1.  ]
 [1.   1.   1.  ]
 [2.25 1.5  1.  ]
 [4.   2.   1.  ]]


# 3D GENERAL ARRAY CREATION FUNCTIONS - np.ones, np.zeros, np.random
These define arrays based on the desired shape. Any dimension can be specified during creation by specifying the dimension and the length along that dimension in a tuple list. All produce data of the float type

In [6]:
#Create a n by m zero matrix
z = np.zeros((2,3)) #creates a 2by 3 zero matrix
print("Zero matrix = \n", z)

zee = np.zeros((2,3,2)) #creates a 3d block matrix of 2by3 matrix with 2 slices
print("Zero matrix of 2 slices =\n", zee)

#Create a n by m matrix of ones matrix
o = np.ones((3,5)) # creates a 3by5 one matrix
print("Ones matrix =\n", o)

#Create an array of random numbers of any dimension
from numpy.random import default_rng
r = default_rng(42).random((2,3))
print("Random 2 by 3 matrix of nos. btw 0 & 1 =\n", r)

Zero matrix = 
 [[0. 0. 0.]
 [0. 0. 0.]]
Zero matrix of 2 slices =
 [[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]
Ones matrix =
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Random 2 by 3 matrix =
 [[0.77395605 0.43887844 0.85859792]
 [0.69736803 0.09417735 0.97562235]]


# REPLICATING, JOINING & MUTATING EXISTIG ARRAYS

In [7]:
#Examples
a = np.array([1,2,3,6,9])
b = a.copy() #doing this preserves the elements of a when operation is performed on b
b += 2 
print('b = \n',b,'\na = \n', a)
b = a #doing this changes the elements of a when an operation is performed on b
b += 2 #This assigns elements of a to b and so changes elements of a when operation is performed on b
print('b = \n',b,'\na = \n', a)

b = 
 [ 3  4  5  8 11] 
a = 
 [1 2 3 6 9]
b = 
 [ 3  4  5  8 11] 
a = 
 [ 3  4  5  8 11]


# COPIES & VIEWS - NO COPY, SHALLOW COPY & DEEP COPY

In [8]:
# NO COPY
a = np.array([[0,1,2,3],
            [4,5,6,7],
            [8,9,10,11]])
b = a # No new object copy is created; b is literally a
x = b.base is a 
print("b is a view of the data in a -",x)
y = b is a
print("b is a - ", y)

#VIEW OR SHALLOW COPY
c = a.view() #
m = c is a
print("c is a - ", m)
n = c.base is a
print("c is a view of the data in a -", n)

#Changing the shape of c doesnt change the shape of a
c = c.reshape((2,6))
print("c shape is ", c.shape)
print("a shape is ", a.shape)

#changing element of c changes element of a
c[0,4] = 1212
print("c = \n", c)
print("a = \n", a)

#Slicing an array returns a view of it
s = a[:,1:3] #slice the 2nd & 3rd columns of a
s[:] = 10 #make all the elements in that slice 10
print(s)
print(a) #a has changed as a result of the slice so deepcopy s before making the slice if u still need a


#DEEP COPY - This makes a copy of the array and its data
a1 = np.arange(int(1e8))
a1.shape
b1 = a1[:50].copy()
print("b is \n", b1)
del a #this removes a from memory - its a large chunk of data

b is a view of the data in a - False
b is a -  True
c is a -  False
c is a view of the data in a - True
c shape is  (2, 6)
a shape is  (3, 4)
c = 
 [[   0    1    2    3 1212    5]
 [   6    7    8    9   10   11]]
a = 
 [[   0    1    2    3]
 [1212    5    6    7]
 [   8    9   10   11]]
[[10 10]
 [10 10]
 [10 10]]
[[   0   10   10    3]
 [1212   10   10    7]
 [   8   10   10   11]]
b is 
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]
