<div class="alert alert-block" style = "background-color: black">
    <p><b><font size="+4" color="orange">Indexing and Slicing using Numpy</font></b></p>
    </div>

* **Import Utilities**

In [20]:
import warnings
warnings.filterwarnings('ignore')

* **Import Data Manipulation Packages**

In [21]:
import numpy as np

---
<div class="alert alert-block" style="background-color: black">
    <p><b><font size="+3" color="white">Indexing in Numpy Arrays</font></b></p>
    </div>
    
---

* **Create a sequence of integers from 10 to 1 in steps of -2**

In [22]:
a = np.arange(10,1,-2)
print("a is ", a)

a is  [10  8  6  4  2]


>Use an array of indices to obtain the elements at those indices

In [23]:
new_array = a[np.array([4,1,2])]
print("new_array is ", new_array)

new_array is  [2 8 6]


>use colon to obtain elements within a range in the array

In [24]:
ele_range = a[2:5]
print("elements within the range 2:5 are ", ele_range)

elements within the range 2:5 are  [6 4 2]


<div class="alert alert-block" style="background-color: orange; border-color: black">
    <p><b><font size="+2" color="black">Slicing and Indexing</font></b></p>
    </div>

### **1. Basic Slicing**

In [25]:
x = np.arange(10) # 1D array
third_element = x[2]
second_tolast = x[-2]
print("x= ",x,"\nthird_element =",third_element,"\nsecond_tolast =",second_tolast)

x=  [0 1 2 3 4 5 6 7 8 9] 
third_element = 2 
second_tolast = 8


### **2. Indexing in n-dimensions**

>Print shape of x

In [26]:
print(x.shape)

(10,)


>change the shape of x from 10 element array to 2by5 2D array

In [27]:
x.shape = (2,5)
print("2D_x is\n", x)

2D_x is
 [[0 1 2 3 4]
 [5 6 7 8 9]]


>Extract elements using indices

In [28]:
x13 = x[1,3]
print("x value in row 1 col 3 is", x13)

x value in row 1 col 3 is 8


x1_1 = x[1,-1]
print("x value in row 1 at the last column is", x1_1)

>Indexing ndarrays with multiple indices

In [29]:
bool = x[0][3] == x[0,3]
print("x[0][3] is the same as x[0,3], the latter is more efficient -",bool)

x[0][3] is the same as x[0,3], the latter is more efficient - True


<div class="alert alert-block" style="background-color: orange; border-color: black">
    <p><b><font size="+2" color="black">N-Dimensional Slicing and Striding</font></b></p>
    </div>

Slicing extends to n-dimensions. Basic slicing occurs when the object is a slice object, a integer, or a tuple of slice objects and integers

Numpy slicing creates a view instead of a copy of the array meaning a view alters the element of the parent array. So care must be taken when extracting from large arrays which may become useless after the slicing. 

This is because the sliced portion contains a reference to the memory of the parent array which will not be released until all arrays derived from it are collected.

<div style="background-color: black">
    <p><b><font size="+2" color="white">1. Sequence Slicing</font></b></p>
    </div>

>Generate a sequence array 

In [30]:
y = np.arange(1,15) #doesn't include 15 in the array
print("y =\n", y)

y =
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]


>Slice y from 1 to 10 in steps of 2

In [31]:
y1_10 = y[1:10:2] 
y1_10

array([ 2,  4,  6,  8, 10])

>Slice y from the beginning up to 8

In [32]:
y[:8] # print everything up to and including 8

array([1, 2, 3, 4, 5, 6, 7, 8])

>Slice y in steps of 2 from the beginning

In [33]:
y[::2] # print everything from the beginning in steps of 2

array([ 1,  3,  5,  7,  9, 11, 13])

>Slice y from 2nd to the last to the 6th to the last element

In [34]:
y_2_6 = y[-2:6:-1]
y_2_6

array([13, 12, 11, 10,  9,  8])

>Slice y from 5th element to the end

In [35]:
y5_end = y[5:]
y5_end

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14])

* **Indexing Multiple items in an array**

In [36]:
a = [1,2,3,4,5]
arr = np.array(a)
print("\nItems at indices 0, 1 & 2 are \n", arr[[0,-1,2]]) #they dont have to be in sequential order


Items at indices 0, 1 & 2 are 
 [1 5 3]


* **Boolean Indexing**

>Index the array where elements are less than 3

In [37]:
arr[arr <= 3]

array([1, 2, 3])

>Index the array where elements are even numbers

In [38]:
arr[arr%2 == 0]

array([2, 4])

<div style="background-color: black">
    <p><b><font size="+2" color="white">2. N-dimensional slicing</font></b></p>
    </div>

First of all in Numpy, 

* 1D array - 1 [ ]
* 2D array - 2[[ ]]
* 3D array - 3[[[ ]]]
* 4D array - 4[[[[ ]]]] and so on

If no.of objects in selection tuple < N, [ : ] is assumed for any dimensions

* **Given a 2D array as follows**

In [51]:
yarray = np.array([[[1],[2],[3]],[[4],[5],[6]]])
yarray

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]]])

>Shape of y is

In [40]:
yarray.shape

(2, 3, 1)

This means that there are 2 3by1 matrix

>Get the first slice of the array matrix

In [41]:
yarray[1,1:3]

array([[5],
       [6]])

* **3-dimensional array**

In [42]:
arr3d = np.array([[[1,2,3],[4,5,6],[7,8,9],[11,12,13]],[[10,20,30],[40,50,60],[70,80,90],[11,12,13]]])
print("Shape of the 3D array\n", arr3d.shape)
print("3D array \n", arr3d)

Shape of the 3D array
 (2, 4, 3)
3D array 
 [[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [11 12 13]]

 [[10 20 30]
  [40 50 60]
  [70 80 90]
  [11 12 13]]]


* **slice a block out of this**

In [43]:
arr3d_block = arr3d[:2,1:3,:2]
print("\n Sliced 3d block [0:2,1:3,:2]\n", arr3d_block)


 Sliced 3d block [0:2,1:3,:2]
 [[[ 4  5]
  [ 7  8]]

 [[40 50]
  [70 80]]]


* **3-dimensional array - another example**

In [45]:
ar3d = np.array([[[1,2,3],[4,5,6],[7,8,9],[11,12,13]],
                  [[10,20,30],[40,50,60],[70,80,90],[11,12,13]],
                  [[11,21,30],[41,51,60],[71,81,90],[11,12,13]],
                  [[12,22,30],[42,52,60],[72,82,90],[11,12,13]]])
print("Shape of the 3D array\n", ar3d.shape)
print("\n3D array \n", ar3d)

Shape of the 3D array
 (4, 4, 3)

3D array 
 [[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [11 12 13]]

 [[10 20 30]
  [40 50 60]
  [70 80 90]
  [11 12 13]]

 [[11 21 30]
  [41 51 60]
  [71 81 90]
  [11 12 13]]

 [[12 22 30]
  [42 52 60]
  [72 82 90]
  [11 12 13]]]


* **Slice another block out of this**

In [52]:
ar3d_block = ar3d[::2,0::4,:2]
print("\n Sliced sheets of 1st and 3rd of the 3D-block [0::2,0::4,:2]\n", ar3d_block)


 Sliced sheets of 1st and 3rd of the 3D-block [0::2,0::4,:2]
 [[[ 1  2]]

 [[11 21]]]


* **4-dimensional array**

In [54]:
arr4d = np.array([[[[1,2,3],[4,5,6],[7,8,9],[11,12,13]],[[10,20,30],[40,50,60],[70,80,90],[11,12,13]]],
                  [[[11,21,30],[41,51,60],[71,81,90],[11,12,13]],[[12,22,30],[42,52,60],[72,82,90],[11,12,13]]],
                  [[[11,21,30],[41,51,60],[71,81,90],[11,12,13]],[[12,22,30],[42,52,60],[72,82,90],[11,12,13]]]])

>Shape of the 4D array is

In [59]:
arr4d.shape

(3, 2, 4, 3)

**This is a 3 set of 4 by 3 matrix in a 2 slice block**

>The 4D array is

In [58]:
 arr4d

array([[[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [11, 12, 13]],

        [[10, 20, 30],
         [40, 50, 60],
         [70, 80, 90],
         [11, 12, 13]]],


       [[[11, 21, 30],
         [41, 51, 60],
         [71, 81, 90],
         [11, 12, 13]],

        [[12, 22, 30],
         [42, 52, 60],
         [72, 82, 90],
         [11, 12, 13]]],


       [[[11, 21, 30],
         [41, 51, 60],
         [71, 81, 90],
         [11, 12, 13]],

        [[12, 22, 30],
         [42, 52, 60],
         [72, 82, 90],
         [11, 12, 13]]]])

>Sliced elements of the 4D array is

In [57]:
 arr4d[0:3,:2,:3,:]

array([[[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[10, 20, 30],
         [40, 50, 60],
         [70, 80, 90]]],


       [[[11, 21, 30],
         [41, 51, 60],
         [71, 81, 90]],

        [[12, 22, 30],
         [42, 52, 60],
         [72, 82, 90]]],


       [[[11, 21, 30],
         [41, 51, 60],
         [71, 81, 90]],

        [[12, 22, 30],
         [42, 52, 60],
         [72, 82, 90]]]])

<div class="alert alert-block" style="background-color: orange; border-color: black">
    <p><b><font size="+2" color="black">Advanced Indexing - Integer or Boolean</font></b></p>
    </div>

* **Indexing in multiple dimensions**

In [49]:
x = np.array([[[1],[2],[3]],[[4],[5],[6]]])

>The shape of x is

In [70]:
 x.shape

(2, 3, 1)

>x slice is

In [71]:
 x[:,:,0]

array([[1, 2, 3],
       [4, 5, 6]])

>The dimension of x is 

In [49]:
x.ndim

The shape of x is  (2, 3, 1)

x slice is 
 [[1 2 3]
 [4 5 6]]

The dimension of x is 
 3


array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]]])

* **To add a new dimension to the selection, use newaxis**

In [61]:
xnew = x[:,:,np.newaxis,:].shape

print(xnew, "is x with a new axis where it is placed")

(2, 3, 1, 1) is x with a new axis where it is placed


> **Newaxis is usefful for combining two arrays**

In [69]:
c = np.arange(5)
c

array([0, 1, 2, 3, 4])

>c_combined is

In [68]:
c_combined = c[:,np.newaxis] + c[np.newaxis,:]
c_combined

array([[0, 1, 2, 3, 4],
       [1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7],
       [4, 5, 6, 7, 8]])

<div style="background-color: black">
    <p><b><font size="+2" color="white">Integer Array Indexing</font></b></p>
    </div>

Allows selection of arbitrary items in an array based on their N-dimensional index

In [73]:
d = np.arange(10,1,-1)
d

array([10,  9,  8,  7,  6,  5,  4,  3,  2])

> Elements of d > 5

In [74]:
d[d>5]

array([10,  9,  8,  7,  6])

In [75]:
d_sel = d[np.array([2,4,1,8])]
d_sel

array([8, 6, 9, 2])

### **Indexing multi-dimensional arrays using integer array**

In [72]:
g = np.arange(35).reshape(5,7)
g

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

**Now this is a 5 by 7 matrix g(r,c) where r and c selection can be an integer array**

In [76]:
selection = g[np.array([0,2,4]),np.array([0,1,2])]

>The selection based on the row and column indices is

In [77]:
selection

array([ 0, 15, 30])

>**Another example**

In [78]:
k = np.array([[1,2],[3,4],[5,6]])
k.shape

(3, 2)

In [79]:
k_sel = k[np.array([0,1,2]),np.array([0,1,0])]

>The selection based on the row and column indices is 

In [80]:
k_sel

array([1, 4, 5])

>**Another example of advanced indexing**

In [81]:
z = np.array([[0,1,2],
              [3,4,5],
              [6,7,8],
              [9,10,11]])
z

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

>**define the row indices**

In [82]:
rows = np.array([[0,0],[3,3]],dtype=np.intp)
rows

array([[0, 0],
       [3, 3]])

>**define the column indices**

In [84]:
cols = np.array([[0,2],[0,2]],dtype=np.intp)
cols

array([[0, 2],
       [0, 2]])

>**The selected elements using advanced indexing are**

In [85]:
 z[rows,cols]

array([[ 0,  2],
       [ 9, 11]])

<div style="background-color: black">
    <p><b><font size="+2" color="white">BOOLEAN ARRAY INDEXING - Useful when filtering element values</font></b></p>
    </div>


>**Find elements of x that are not a number (nan)**

In [87]:
w = np.array([[1.,2.],[np.nan,3.],[np.nan,np.nan]])
w

array([[ 1.,  2.],
       [nan,  3.],
       [nan, nan]])

>ELements of w that are not a number are

In [89]:
non_nan = w[~np.isnan(w)]
non_nan

array([1., 2., 3.])

>**Add a constant to all negative values**

In [90]:
u = np.array([1., -1, -2, 3, -4])
u

array([ 1., -1., -2.,  3., -4.])

In [91]:
u_neg = u[u<0]
u_neg

array([-1., -2., -4.])

>Negative values of u plus a costant

In [92]:
u_negplusconst = u_neg + 20
u_negplusconst

array([19., 18., 16.])

>**Explore the two different coding styles**

In [93]:
u[u<0] = u[u<0] +20
u

array([ 1., 19., 18.,  3., 16.])

>**or**

In [94]:
unew[unew<0] += 20
unew

array([ 1., 19., 18.,  3., 16.])

### **Boolean indexing another way**

In [86]:
t = np.arange(35).reshape(5,7)
t

>**define a boolean array that meets a specific condition**

In [86]:
b = t>20
b

>print the 5th column

In [95]:
b[:,5]
t[b[:,5]]

array([[21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

>**Given an array select all rows which sum up to less than or equal to 2**

In [96]:
s = np.array([[0,1],[1,1],[2,2]])
s.shape

(3, 2)

>**s.sum(-1) sum array alog the axis provided**

In [98]:
rowsum = np.sum(s,-1)
rowsum

array([1, 2, 4])

>Use Boolean to select all rows adding up to an even number & use advanced integer index to select columns 0 & 2

In [99]:
mat = np.array([[0,1,2],
                [3,4,5],
                [6,7,8],
                [9,10,11]])
mat

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [86]:
rows = np.sum(mat,-1)%2 == 0; 

>Rows that sum to even numbers

In [100]:
rows

array([False,  True, False,  True])

In [101]:
cols = np.array([0,2])

>Columns 0 & 2

In [86]:
cols

>Selected rows from the given matrix is give as

In [102]:
mat = mat[np.ix_(rows,cols)]
mat

array([[ 3,  5],
       [ 9, 11]])

>**Use a 2D boolaean array of shape (2,3)with 4 true elements to select rows from a (2,3,5) array to give a (4,5) 2D array**

In [106]:
arr235 = np.arange(30).reshape(2,3,5)
arr235

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

>The boolean selection array of 2 by 3

In [108]:
boolarray_rows = np.array([[True,False,True],[True,False,True]])
boolarray_rows

array([[ True, False,  True],
       [ True, False,  True]])

>The selected rows using the boolean condition is given as:

In [109]:
row_selection = arr235[boolarray_rows]
row_selection

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [25, 26, 27, 28, 29]])

**What this does is to go down the rows of the 235 array and select the row indices where the boolean value is true**

This means given rows[0,1,2,3,4,5], and boolean array[T,F,T,T,F,T), only rows[0,2,3,5] will be selected


# COMBINED ADVANCED & BASIC INDEXING

In [ ]:
#Example - Make a selection by combining integer array indexing and slicing operation
r = np.arange(35).reshape(5,7)
print("\nr is\n", r)
#select the columns 1&2 of the rows 0,2&4
r_sel = r[np.array([0,2,4]),1:3]
print("\nThe selected rows are obtained by combining integer array and slicing operation\n", r_sel)

#Alternatively, select the columns first before the rows
r_newsel = r[:,1:3][np.array([0,2,4]),:]
print("\nThe selected rows are obtained by first selecting the columns before the rows\n", r_newsel)

#Using a single advanced index to replace a slice to get the same result
q = np.arange(12).reshape(4,3)
print("\nq is ", q)
#Now use a slice to select rows and columns
q_slice = q[1:2,1:3] #indices of rows and columns are represented by a slice
print("\n The slice of rows and columns selected is using 2 slices\n", q_slice)
print("\nq hasn't changed\n", q)
#Now use a single advanced index to replace a slice either for row or column
q_advIndex = q[1:2,[1,2]]
print("\nThe selection obtained using a single advanced index and a slice \n", q_advIndex)

#You can also use the function np.take to 
print(list(range(100)))

# APPLICATION OF SLICING & INDEXING TO MACHINE LEARNING


# TWO DIMENSIONAL SLICING 
There are two examples of 2D slicing that you will encounter in machine learning

# SPLIT INPUT & OUTPUT FEATURES
It is common to split your loaded data into input(X) and output variables(Y)
How do we do this?
1. We can do this by slicing all rows and all columns up to but before the last column, then separately indexing the last column
2. For the input features, we can select all rows and all columns except the last one by specifying : for in the rows index and :-1 in the columns index

In [ ]:
# Example
import numpy as np
#define array
data = np.array([[11,22,33],
               [44,55,66],
               [77,88,99]])
#Separate the data ito input ad output
x = data[:,:-1] #input variables
y = data[:,-1] #output variables
print("x=\n",x)
print("\ny =\n", y)

# SPLIT TRAIN & TEST ROWS
Splitting into train and test sets involves splitting of rows where some portion will be used to train the model and the remaining portion will be used to estimate the skill of the trained model. 
1. The training dataset would be all rows to the beginning of the split point
2. The test dataset will be all rows starting from the split point to the end of the dimension


In [ ]:
#Example Split Train & Test Data
#define array
dataset = np.array([[11,22,33],
                    [44,55,66],
                    [77,88,99]])
#Separate the data
split = 2
train,test = data[:split,:],data[split:,:]
print("train set \n", train)
print("\ntest set \n", test)

# PRACTICALS

In [ ]:
# 1. DEVELOP YOUR OWN EXAMPLE 