# INDEXING & SLICING ON LISTS & NUMPY NDARRAYS

In [1]:
# INDEXING NUMPY ARRAYS
import numpy as np
#Create a sequence of integers from 10 to 1 in steps of -2
a = np.arange(10,1,-2)
print("a is \n", a)
#Use an array of indices to obtain the elements at those indices
new_array = a[np.array([4,1,2])]
print("new_array is\n", new_array)
#use colon to obtain elements within a range in the array
ele_range = a[2:5]
print("elements within the range 2:5 are\n", ele_range)

a is 
 [10  8  6  4  2]
new_array is
 [2 8 6]
elements within the range 2:5 are
 [6 4 2]


# TYPES OF INDEXING IN NUMPY ARRAY - Basic Slicing & Indexing 

# Basic Slicing

In [2]:
#1. Single Element Indexing
x = np.arange(10) # 1D array
third_element = x[2]
second_tolast = x[-2]
print("x=\n",x,"\nthird_element=",third_element,"\nsecond_tolast=",second_tolast)
x[4]

x=
 [0 1 2 3 4 5 6 7 8 9] 
third_element= 2 
second_tolast= 8


4

In [3]:
#2. Indexing in n-dimensions
print(x.shape)
#change the shape of x from 10 element array to 2by5 2D array
x.shape = (2,5)
print("2D_x is\n", x)
#Extract elements using indices
x13 = x[1,3]
print("x value in row 1 col 3 is", x13)
x1_1 = x[1,-1]
print("x value in row 1 at the last column is", x1_1)
#Indexing ndarrays with multiple indices
bool = x[0][3] == x[0,3]
print("x[0][3] is the same as x[0,3], the latter is more efficient -",bool)

(10,)
2D_x is
 [[0 1 2 3 4]
 [5 6 7 8 9]]
x value in row 1 col 3 is 8
x value in row 1 at the last column is 9
x[0][3] is the same as x[0,3], the latter is more efficient - True


# Slicing & Striding
Slicing extends to n-dimensions. Basic slicing occurs when the object is a slice object, a integer, or a tuple of slice objects and integers
Numpy slicing creates a view instead of a copy of the array meaning a view alters the element of the parent array. So care must be taken when extracting from large arrays which may become useless after the slicing. This is because the sliced portion contains a reference to the memory of the parent array which will not be released until all arrays derived from it are collected.

In [4]:
#3. Sequence Slicing
y = np.arange(1,15) #doesn't include 15 in the array
print("y =\n", y)

y1_10 = y[1:10:2] #doesn't include 10 in the array
print("\ny from 1 to 10 in steps of 2 =\n", y1_10)

print("\ny from the begining up to 8\n", y[:8]) # print everything up to and including 8

print("\ny in steps of 2 from the beginning \n", y[::2]) # print everything from the beginning in steps of 2

print("y =\n", y)

y_2_6 = y[-2:6:-1]
print("\ny from 2nd to the last to the 6th =\n",y_2_6)

y5_end = y[5:]
print("\ny from 5 to the end =\n", y5_end)

#Indexing Multiple items in an array
a = [1,2,3,4,5]
arr = np.array(a)
print("\nMultiple items can be indexed thus\n", arr[[0,-1,2]]) #they dont have to be in sequential order

#Boolean Indexing
arr_lt3 = print("\nPrint the array where elements are less than 3\n", arr[arr <= 3])

arr_even = print("\nPrint the array elements that are even numbers\n", arr[arr%2 == 0])

y =
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]

y from 1 to 10 in steps of 2 =
 [ 2  4  6  8 10]

y from the begining up to 8
 [1 2 3 4 5 6 7 8]

y in steps of 2 from the beginning 
 [ 1  3  5  7  9 11 13]
y =
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]

y from 2nd to the last to the 6th =
 [13 12 11 10  9  8]

y from 5 to the end =
 [ 6  7  8  9 10 11 12 13 14]

Multiple items can be indexed thus
 [1 5 3]

Print the array where elements are less than 3
 [1 2 3]

Print the array elements that are even numbers
 [2 4]


In [5]:
# N-dimensional slicing
# First of all 1D array - 1 [], 2D array - 2[[]], 3D array - 3[[[]]], 4D array - 4[[[[]]]] and so on
#If no.of objects in selection tuple < N : is assumed for any dimensions
yarray = np.array([[[1],[2],[3]],[[4],[5],[6]]])
print(yarray)
print("\nyarray is a", yarray.shape, "matrix\n i.e there are 2 3by1 matrix")
yarray[1,1:3]

#3-dimensional array
arr3d = np.array([[[1,2,3],[4,5,6],[7,8,9],[11,12,13]],[[10,20,30],[40,50,60],[70,80,90],[11,12,13]]])
print("Shape of the 3D array\n", arr3d.shape)
print("3D array \n", arr3d)
#slice a block out of this
arr3d_block = arr3d[:2,1:3,:2]
print("\n Sliced 3d block [0:2,1:3,:2]\n", arr3d_block)

#3-dimensional array - another example
ar3d = np.array([[[1,2,3],[4,5,6],[7,8,9],[11,12,13]],
                  [[10,20,30],[40,50,60],[70,80,90],[11,12,13]],
                  [[11,21,30],[41,51,60],[71,81,90],[11,12,13]],
                  [[12,22,30],[42,52,60],[72,82,90],[11,12,13]]])
print("Shape of the 3D array\n", ar3d.shape)
print("3D array \n", ar3d)
#slice a block out of this
ar3d_block = ar3d[::2,0::4,:2]
print("\n Sliced sheets of 1st and 3rd of the 3D-block [0::2,0::4,:2]\n", ar3d_block)

#4-dimensional array
arr4d = np.array([[[[1,2,3],[4,5,6],[7,8,9],[11,12,13]],[[10,20,30],[40,50,60],[70,80,90],[11,12,13]]],
                  [[[11,21,30],[41,51,60],[71,81,90],[11,12,13]],[[12,22,30],[42,52,60],[72,82,90],[11,12,13]]],
                  [[[11,21,30],[41,51,60],[71,81,90],[11,12,13]],[[12,22,30],[42,52,60],[72,82,90],[11,12,13]]]])
print("Shape of the 4D array is",arr4d.shape)
print("\nThe 4D array is \n", arr4d)
print("\n Sliced elements of the 4D array is \n", arr4d[0:3,:2,:3,:])




[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]]

yarray is a (2, 3, 1) matrix
 i.e there are 2 3by1 matrix
Shape of the 3D array
 (2, 4, 3)
3D array 
 [[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [11 12 13]]

 [[10 20 30]
  [40 50 60]
  [70 80 90]
  [11 12 13]]]

 Sliced 3d block [0:2,1:3,:2]
 [[[ 4  5]
  [ 7  8]]

 [[40 50]
  [70 80]]]
Shape of the 3D array
 (4, 4, 3)
3D array 
 [[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [11 12 13]]

 [[10 20 30]
  [40 50 60]
  [70 80 90]
  [11 12 13]]

 [[11 21 30]
  [41 51 60]
  [71 81 90]
  [11 12 13]]

 [[12 22 30]
  [42 52 60]
  [72 82 90]
  [11 12 13]]]

 Sliced sheets of 1st and 3rd of the 3D-block [0::2,0::4,:2]
 [[[ 1  2]]

 [[11 21]]]
Shape of the 4D array is (3, 2, 4, 3)

The 4D array is 
 [[[[ 1  2  3]
   [ 4  5  6]
   [ 7  8  9]
   [11 12 13]]

  [[10 20 30]
   [40 50 60]
   [70 80 90]
   [11 12 13]]]


 [[[11 21 30]
   [41 51 60]
   [71 81 90]
   [11 12 13]]

  [[12 22 30]
   [42 52 60]
   [72 82 90]
   [11 12 13]]]


 [[[11 21 30]
   [41 51 60]
   [7

# ADVANCED INDEXING - INTEGER OR BOOLEAN

In [6]:
#Indexing in multiple dimensions
x = np.array([[[1],[2],[3]],[[4],[5],[6]]])
print("The shape of x is ", x.shape)
print("\nx slice is \n", x[:,:,0])
print("\nThe dimension of x is \n",x.ndim)

#To add a ew dimension to the selection, use newaxis
xnew = x[:,:,np.newaxis,:].shape
print(xnew, "is x with a new axis where it is placed")

#Newaxis is usefful for combining two arrays
c = np.arange(5)
c_combined = c[:,np.newaxis] + c[np.newaxis,:]
print("\nc_combined is \n", c_combined)

The shape of x is  (2, 3, 1)

x slice is 
 [[1 2 3]
 [4 5 6]]

The dimension of x is 
 3
(2, 3, 1, 1) is x with a new axis where it is placed

c_combined is 
 [[0 1 2 3 4]
 [1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]
 [4 5 6 7 8]]


# INTEGER ARRAY INDEXING
Allows selection of arbitrary items in an array based on their N-dimensional index

In [7]:
d = np.arange(10,1,-1)
print("\nd is \n", d)
d_sel = d[np.array([2,4,1,8])]
print("\nSelected items in d are \n", d_sel)
print("\n Elements of d > 5 \n", d[d>5])

#Indexing multi-dimensional arrays using integer array
g = np.arange(35).reshape(5,7)
print("\n g is \n", g)
#Now this is a 5 by 7 matrix g(r,c) where r and c selection can be an integer array
selection = g[np.array([0,2,4]),np.array([0,1,2])]
print("\n The selection based on the row and column indices is \n", selection)

#Another example
k = np.array([[1,2],[3,4],[5,6]])
print("Shape of k is \n", k.shape)
k_sel = k[np.array([0,1,2]),np.array([0,1,0])]
print("\n The selection based on the row and column indices is \n", k_sel)

#Another example of advanced indexing
z = np.array([[0,1,2],
              [3,4,5],
              [6,7,8],
              [9,10,11]])
#define the row indices
rows = np.array([[0,0],[3,3]],dtype=np.intp)
#define the column indices
cols = np.array([[0,2],[0,2]],dtype=np.intp)
print("\nThe selected elements using advanced indexing are \n", z[rows,cols])


d is 
 [10  9  8  7  6  5  4  3  2]

Selected items in d are 
 [8 6 9 2]

 Elements of d > 5 
 [10  9  8  7  6]

 g is 
 [[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]]

 The selection based on the row and column indices is 
 [ 0 15 30]
Shape of k is 
 (3, 2)

 The selection based on the row and column indices is 
 [1 4 5]

The selected elements using advanced indexing are 
 [[ 0  2]
 [ 9 11]]


In [12]:
# BOOLEAN ARRAY INDEXING Usefulwhe filtering element values
w = np.array([[1.,2.],[np.nan,3.],[np.nan,np.nan]])
non_nan = w[~np.isnan(w)] #find elements of x that are not a number (nan)
print("ELements of w that are not a number are", non_nan)

#Add a constant to all negative values
u = np.array([1., -1, -2, 3, -4])
u_neg = u[u<0]
u_negplusconst = u_neg + 20
print("Negative values of u plus a costant\n", u_negplusconst)

#Explore the two different coding styles
unew = u
#or simply put
u[u<0] = u[u<0] +20
print(u)
#or
unew[unew<0] += 20
print(unew)

#Boolean indexing another way ?????????????????????????
t = np.arange(35).reshape(5,7)
print("\t is \n", t)
#define a boolean array that meets a specific condition
b = t>20
print(b)
b[:,5] #print the 5th column
t[b[:,5]]

#Boolean Indexing - Given an array select all rows which sum up to less than or equal to 2
s = np.array([[0,1],[1,1],[2,2]])
print("\n Shape of s is \n", s.shape)
rowsum = np.sum(s,-1) #or s.sum(-1) sum array alog the axis provided
print("\nSum across all rows is \n", rowsum)

#Use Boolean to select all rows adding up to an even number & use advanced integer idex to select columns 0 & 2
mat = np.array([[0,1,2],
                [3,4,5],
                [6,7,8],
                [9,10,11]])
rows = np.sum(mat,-1)%2 == 0; print("\nrows that sum to even numbers -", rows)
cols = np.array([0,2]); print("\n columns 0 & 2 - ", cols)
mat = mat[np.ix_(rows,cols)]; print("\n Selected rows from the given matrix is give as\n", mat)

#Use a 2D boolaean array of shape (2,3)with 4 true elements to select rows from a (2,3,5) array to give a (4,5) 2D array
arr235 = np.arange(30).reshape(2,3,5)
print("\n The 2 by 3 by 5 array is \n", arr235)
boolarray_rows = np.array([[True,False,True],[True,False,True]]) #the boolean selection array of 2 by 3
row_selection = arr235[boolarray_rows]
print("\n The selected rows using the boolean condition is given as \n", row_selection)
print("\nWhat this does is to go down the rows of the 235 array and select the row indices where the boolean value is true\n")
print("This means given rows[0,1,2,3,4,5], and boolean array[T,F,T,T,F,T), only rows[0,2,3,5] will be selected")

ELements of w that are not a number are [1. 2. 3.]
Negative values of u plus a costant
 [19. 18. 16.]
[ 1. 19. 18.  3. 16.]
[ 1. 19. 18.  3. 16.]
	 is 
 [[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]]
[[False False False False False False False]
 [False False False False False False False]
 [False False False False False False False]
 [ True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True]]

 Shape of s is 
 (3, 2)

Sum across all rows is 
 [1 2 4]

rows that sum to even numbers - [False  True False  True]

 columns 0 & 2 -  [0 2]

 Selected rows from the given matrix is give as
 [[ 3  5]
 [ 9 11]]

 The 2 by 3 by 5 array is 
 [[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]

 The selected rows using the boolean condition is given as 
 [[ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [25 26 27 28 29]]

What 

# COMBINED ADVANCED & BASIC INDEXING

In [30]:
#Example - Make a selection by combining integer array indexing and slicing operation
r = np.arange(35).reshape(5,7)
print("\nr is\n", r)
#select the columns 1&2 of the rows 0,2&4
r_sel = r[np.array([0,2,4]),1:3]
print("\nThe selected rows are obtained by combining integer array and slicing operation\n", r_sel)

#Alternatively, select the columns first before the rows
r_newsel = r[:,1:3][np.array([0,2,4]),:]
print("\nThe selected rows are obtained by first selecting the columns before the rows\n", r_newsel)

#Using a single advanced index to replace a slice to get the same result
q = np.arange(12).reshape(4,3)
print("\nq is ", q)
#Now use a slice to select rows and columns
q_slice = q[1:2,1:3] #indices of rows and columns are represented by a slice
print("\n The slice of rows and columns selected is using 2 slices\n", q_slice)
print("\nq hasn't changed\n", q)
#Now use a single advanced index to replace a slice either for row or column
q_advIndex = q[1:2,[1,2]]
print("\nThe selection obtained using a single advanced index and a slice \n", q_advIndex)

#You can also use the function np.take to 
print(list(range(100)))


r is
 [[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]]

The selected rows are obtained by combining integer array and slicing operation
 [[ 1  2]
 [15 16]
 [29 30]]

The selected rows are obtained by first selecting the columns before the rows
 [[ 1  2]
 [15 16]
 [29 30]]

q is  [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

 The slice of rows and columns selected is using 2 slices
 [[4 5]]

q hasn't changed
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

The selection obtained using a single advanced index and a slice 
 [[4 5]]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98,

# APPLICATION OF SLICING & INDEXING TO MACHINE LEARNING


# TWO DIMENSIONAL SLICING 
There are two examples of 2D slicing that you will encounter in machine learning

# SPLIT INPUT & OUTPUT FEATURES
It is common to split your loaded data into input(X) and output variables(Y)
How do we do this?
1. We can do this by slicing all rows and all columns up to but before the last column, then separately indexing the last column
2. For the input features, we can select all rows and all columns except the last one by specifying : for in the rows index and :-1 in the columns index

In [ ]:
# Example
import numpy as np
#define array
data = np.array([[11,22,33],
               [44,55,66],
               [77,88,99]])
#Separate the data ito input ad output
x = data[:,:-1] #input variables
y = data[:,-1] #output variables
print("x=\n",x)
print("\ny =\n", y)

# SPLIT TRAIN & TEST ROWS
Splitting into train and test sets involves splitting of rows where some portion will be used to train the model and the remaining portion will be used to estimate the skill of the trained model. 
1. The training dataset would be all rows to the beginning of the split point
2. The test dataset will be all rows starting from the split point to the end of the dimension


In [8]:
#Example Split Train & Test Data
#define array
dataset = np.array([[11,22,33],
                    [44,55,66],
                    [77,88,99]])
#Separate the data
split = 2
train,test = data[:split,:],data[split:,:]
print("train set \n", train)
print("\ntest set \n", test)

train set 
 [[11 22 33]
 [44 55 66]]

test set 
 [[77 88 99]]


# PRACTICALS

In [ ]:
# 1. DEVELOP YOUR OWN EXAMPLE 