<div class="alert alert-block" style = "background-color: black">
    <p><b><font size="+4" color="orange">Broadcasting Computation on Numpy Arrays</font></b></p>
    </div>

In [5]:
import warnings
warnings.filterwarnings('ignore')

* **Import Data Manipulation Packages**

In [4]:
import numpy as np

---
<div class="alert alert-block" style="background-color: black">
    <p><b><font size="+3" color="white">Introduction</font></b></p>
        <p><b><font size="+2" color="white">Broadcasting</font></b></p>
    </div>
    
---

Broadcasting is a set of rules for applying binary universal functions on arrays of different sizes

### **For arrays of the same size, operations are performed on an element by element basis**

> **Example - Adding a scalar to a 1D-array**

In [10]:
q = np.array([1, 2, 3])
s = 2
bcast = q + s
bcast

array([3, 4, 5])

> **Example - For a scalar and a 2D-array**

In [9]:
A2D = np.array([[1,2,3],[1,2,3]])
s = 3
bcast1 = A2D + s
bcast1

array([[4, 5, 6],
       [4, 5, 6]])

>**Example - For two 1D arrays**

In [12]:
a = np.array([0,1,2]) #1D-array
b = np.array([5,5,5]) #1D-array

>a + b

In [13]:
 a+b

array([5, 6, 7])

In [4]:
#Example - For a higher dimension array
#Adding 1D-array to 2D-array
M = np.array([[1,2,3],[1,2,3]]) #2d array
p = np.array([5,6,7]) #1D array
print("\nbroadcast = \n", M+p)
print("\nWhat this does is to add the corresponding elements with the corresponding indices")


broadcast = 
 [[ 6  8 10]
 [ 6  8 10]]

What this does is to add the corresponding elements with the corresponding indices


## Limitations on broadcasting

### Arithmetic or Broadcasting can only be performed when the shape of each dimension in the arrays are equal or one has the dimension size of 1

In [5]:
# Example compare the shapes of the arrays before attempting broadcasting
print(M.shape)
print(p.shape)
print("Numpy attempts to compare the two by comparing the column dimensions \
if they are equal, the broadcastwill be successful")

#Example where broadcasting will not be successful
A = np.array([[1,2,3],[1,2,3]])
print(A.shape)
#define a 1D array
b = np.array([[1,2]])
print(b.shape)

#attempt broadcast
## C = A + b
#print(C)

(2, 3)
(3,)
Numpy attempts to compare the two by comparing the column dimensions if they are equal, the broadcastwill be successful
(2, 3)
(1, 2)


## Practice

In [6]:
# Create three new and different examples of broadcasting with Numpy Arrays
# Scalar and nd-array
nd = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(nd.shape)
scalar = 2 #the dimension of this scalar will be converted to a 
print(nd*scalar)

# 1D array and nd-array
vec = np.array([2,2,2])
print("\n 1D array times nd array \n", vec * nd)
print("You will see that the result of the scalar and the vector in this case are same.\
This is because numpy compares the dimension of the two columns in both arrays and finds\
 them to be the same")

#Two nd-arrays
nd1 = np.array([[1,2,3],[5,6,7]]) #2X3 array
nd2 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]) #2X2X3 array
nd1 + nd2


(2, 2, 3)
[[[ 2  4  6]
  [ 8 10 12]]

 [[14 16 18]
  [20 22 24]]]

 1D array times nd array 
 [[[ 2  4  6]
  [ 8 10 12]]

 [[14 16 18]
  [20 22 24]]]
You will see that the result of the scalar and the vector in this case are same.This is because numpy compares the dimension of the two columns in both arrays and finds them to be the same


array([[[ 2,  4,  6],
        [ 9, 11, 13]],

       [[ 8, 10, 12],
        [15, 17, 19]]])

## Broadcasting Rules

### Rule 1: If the two arrays differ in their number of dimensions, the shape of the one with fewer dimensions is padded with ones on its leading (left) side.

### Rule 2: If the shape of the two arrays does not match in any dimension, the array with shape equal to 1 in that dimension is stretched to match the other shape.

### Rule 3: If in any dimension the sizes disagree and neither is equal to 1, an error is raised.

In [7]:
# Example 1
M = np.ones((2,3))
x = np.arange(3)
print("\nM.shape = ",M.shape)
print("\nx.shape = ",x.shape)


M.shape =  (2, 3)

x.shape =  (3,)


#### Rule 1 demands that we pad the dimension of array x with ones on the left since it has fewer dimensions than array M 
M.shape -> (2,3)
x.shape -> (1,3)

By rule 2, we see that the first dimension of x disagrees, so we stretch this dimension to match that of M
M.shape -> (2,3)
x.shape -> (2,3)

The shapes match and we see that the final shape will be (2,3)


In [8]:
print(M + x)

[[1. 2. 3.]
 [1. 2. 3.]]


In [9]:
#Example 2 - Here we consider a situation where both arrays need to be broadcast

a = np.arange(3).reshape((3,1))
b = np.arange(3)
#Get the shape of the arrays
print(a.shape)
print(b.shape)

(3, 1)
(3,)


#### Rule 1 demands that we pad the dimension of array b with ones on the left since it has fewer dimensions than array a 
a.shape -> (3,1)
b.shape -> (1,3)

#### And Rule 2 tells us that we upgrade each of a and b dimensions with ones to match the size of the array a i.e match the no. of rows of array a
a.shape -> (3,3)
b.shape -> (3,3)

#### Because these results match,the shapes are now compatible and the result will be a 3 by3 matrix



In [10]:
a + b
print(a + b)

[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [12]:
#Example 3 - Here we look at two incompatible arrays
N = np.ones((3,2))
z = np.arange(3)
#Get the shape of the arrays
print(N.shape)
print(z.shape)

(3, 2)
(3,)


#### Rule 1 demands that we pad the dimension of array z with ones on the left since it has fewer dimensions than array aN
N.shape -> (3,2)
z.shape -> (1,3)

#### And Rule 2 tells us that we upgrade the dimension of z with ones to match the size of the array N i.e match the no. of rows of array N
N.shape -> (3,2)
z.shape -> (3,3)

#### And by rule 3, the final shapes do not match, so these two arrays are incompatible
N + z -> ValueError operands could not be broadcast together with shapes (3,2) (3,)

## Broadcasting in Practice
## Centering and Array

In [20]:
# Given an array of 10 observations each with 3 values
x = np.random.random((10,3))
print(x)
#We compute the mean of each feature using the mean aggregate across the dimension
xmean = np.mean(x,0)
print("\n",xmean)
#To center the x-array we subtract the mean, this is a broadcasting operation
x_centered = x - xmean
#Confirm that the centered array has a near zero mean
print("\n Centered array has a near zero value as shown\n", x_centered.mean(0))


[[0.45897473 0.36819215 0.61276118]
 [0.26079943 0.95450655 0.98384252]
 [0.8292296  0.87519069 0.41453232]
 [0.424938   0.05864036 0.19730316]
 [0.93898779 0.47647737 0.09774199]
 [0.51181257 0.923175   0.84312744]
 [0.50531206 0.61423892 0.94279246]
 [0.13391706 0.43187526 0.16322003]
 [0.17013803 0.0146778  0.42369664]
 [0.83368675 0.4210263  0.51046255]]

 [0.5067796  0.51380004 0.51894803]

 Centered array has a near zero value as shown
 [-2.22044605e-17 -3.33066907e-17 -2.22044605e-17]
